---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- include_vars: "default.yml"
  tags: [always]

- include: install.yml

- include: configure.yml
  when: haproxy_manage_config
